### PR TITLE
Added peft package

### PR DESCRIPTION
**Pull request by VictorCallejas**

### CODE REVIEW

**Comment by klwetstone** [comment]
@VictorCallejas merged! The code execution runtime may take an hour or so to update.

**Comment by VictorCallejas** [comment]
Perfect, thank you Katie. Have a nice one!

**Comment by klwetstone** [comment]
@VictorCallejas Another runtime package request was recently submitted that requires peft <= 0.11.0. Would your submission work with peft 0.11.0 instead of peft 0.12.0?

**Comment by VictorCallejas** [comment]
I am using a method that was introduced in 0.12.0, but this method is only for inizialization so maybe it works with 0.11.0 for inference on test. I will test with a subsmission in the next couple of days and let you know

**Comment by klwetstone** [comment]
@VictorCallejas Have you had a chance to check whether peft 0.11.0 will work for you? Thanks!

**Comment by VictorCallejas** [comment]
Yes, will work for inference, so we can downgrade the peft version, thanks!

**Comment by klwetstone** [comment]
Thank you for being flexible and looking into it!

**Pull request merged**
