### PR TITLE
Add peft, lmdeploy, protobuf packages

### PR DESCRIPTION
**Pull request by qadn0**
Hello @klwetstone, I added the `peft` 0.11.0 to the gpu environment and kept the `peft` 0.12.0 for the cpu environment. Since I only installed `lmdeploy` for the gpu. I hope this works.

### CODE REVIEW

**Comment by klwetstone** [comment]
@qadn0 We're still checking with another participant about changing the version of the peft package in the current environment. Thank you for your patience! We'll work on merging this in as soon as we hear from them.

**Comment by klwetstone** [comment]
@qadn0 I'm looking over this PR and will push any necessary changes. A few questions in the meantime:

- Is there a reason you updated the installation of `xformers` in your PR? A package should only be installed from pypi if it is not available from conda-forge. The previous `xformers` installation is both faster, and ensures that `xformers` plays nicely with the installations of CUDA and pytorch.
- Do you need a specific version of `protobuf`? The current changes use version 5.28.2. That isn't available on conda-forge, but it looks like version 5.27.5 is.

**Comment by qadn0** [comment]
Hey @klwetstone,

- I'm having trouble installing the `vllm` package, and it seems like the `xformers` package is unavailable. I think the package installed by conda might not be recognized when using pip. Here's the error message I'm getting:

```
WARN resolve_pypi{group=gpu platform=linux-64}: install_wheel_rs::metadata: The .dist-info directory lmdeploy-0.6.0 does not start with the normalized version: 0.6.0+cu118
  × failed to solve the pypi requirements of 'gpu' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because there is no version of xformers==0.0.23.post1 and
      vllm==0.4.0+cu118 depends on xformers==0.0.23.post1, we can conclude
      that vllm==0.4.0+cu118 cannot be used.
      And because only vllm==0.4.0+cu118 is available and you require vllm, we
      can conclude that the requirements are unsatisfiable.
```

- Protobuf version 5.27.5 is fine. Thanks for letting me know.

**Comment by qadn0** [comment]
Hi @klwetstone 
I noticed that you merged to the main branch, but when I checked, the packages weren't there. Do I need to do something else on my side?

**Comment by klwetstone** [comment]
@qadn0 I merged to the main branch of your forked repository -- I had a few changes to push, and was resolving them with the changes you had made.

The `vllm` [installation](https://docs.vllm.ai/en/stable/getting_started/installation.html) may still need some work. Based on the docs, it's not clear whether the current method of installation is correctly using the existing pytorch and cuda runtime packages, versus installing new versions with pip. Based on the changes to `pixi.lock`, a number of cuda runtime packages are now being downloaded from the pytorch pip repo that is added (eg `nvidia-cuda-runtime-cu11`).

Because of the complexity, this may take a longer to get merged. It would be helpful on your end to work through installing vllm with CUDA and pytorch already installed, and make sure those package aren't re-installed. Based on the vllm [docs](https://docs.vllm.ai/en/stable/getting_started/installation.html#build-from-source), it's not clear whether this is possible when installing via pip and a specific wheel.

**Comment by klwetstone** [comment]
@qadn0 I would recommend removing vllm from this PR, so we can make protobuf and lmdeploy available for you more quickly.

Then you can create a separate PR that adds vllm without re-installing other packages. From the [documentation](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source-with-compilation), it looks like that will likely need to be done by building from source

**Comment by qadn0** [comment]
Hi @klwetstone -- I removed the `vllm` package from this PR. Please merge the `protobuf` and `lmdeploy` packages. Thanks for your support.

**Comment by klwetstone** [comment]
Hi @qadn0 -- apologies for the delay in response. We were looking into the way pip installs `lmdeploy`'s CUDA dependencies. Similar to `vllm`, when `lmdeploy` is installed via PyPI it installs its own version of a variety of CUDA-related packages. You can see this in `pixi.lock` with the additional of new pypi packages for things like `nvidia-cuda-runtime-cu11`. 

When `lmdeploy` is installed, we instead want to use the existing CUDA packages that are already installed via conda forge. This may require a more complex installation process. For example, it's possible that running `pip install lmdeploy --no-deps` in the `Dockerfile` would install correctly (pip documentation [here](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-deps)).

The process could be:
1. Install all `lmdeploy` dependencies explicitly on their own
2. Get pip to install `lmdeploy` without installing any of its dependencies, eg. with `--no-deps`

When `lmdeploy` is installed via `pip`, `pip` will check that `lmdeploy`'s dependencies are available and install any that are needed. However, it will *not* detect that CUDA packages were already installed, because they were installed with conda-forge.

**Comment by klwetstone** [comment]
@qadn0 I see that you made a couple changes here. I see that there are a few new CUDA packages that get installed via pip:

```
[feature.gpu.pypi-dependencies]
nvidia-nccl-cu11 = {version = "==2.21.5"}
nvidia-cuda-runtime-cu11 = {version = "==11.8.89"}
nvidia-cublas-cu11 = {version = "==11.11.3.6"}
nvidia-curand-cu11 = {version = "==10.3.0.86"}
```

The goal is to only install CUDA once. All packages should use the existing runtime CUDA that is installed with conda-forge. Did you check whether you are able to use`lmdeploy` successfully without adding the new CUDA packages (ie. with only the CUDA installed via conda-forge)?

Thank you for working through the alternate installation! We know these things can be finicky.

**Comment by bamps53** [comment]
@klwetstone

What is allowed change to runtime?
I'd like to add vllm, but it seems rejected here.

Also, there are a lot of effort to make llm faster happen in pytorch 2.4~ and cuda12.x world.  Is it ok to change base image from `ghcr.io/prefix-dev/pixi:0.26.1-jammy-cuda-11.8.0` to `ghcr.io/prefix-dev/pixi:0.33.0-focal-cuda-12.2.2`?

**Comment by klwetstone** [comment]
@bamps53 Good question. Changes to the runtime shouldn't break any solutions that were previously able to run. Switching from CUDA 11.8 to CUDA 12 would likely do this, so any changes must still use the same base image. We are considering moving to CUDA 12 for future code execution competitions.

The implementation of `vllm` here was not merged because it installed a separate version of CUDA, rather than using the existing version installed in the runtime by conda-forge. To add `vllm`, you would need to figure out how to install it with an existing CUDA and pytorch. There is some relevant discussion earlier in this conversation, both about `vllm` and about possibly using the `--no-deps` flag when installing with pip.

Good luck!

FYI, there is a second DrivenData [competition](https://www.drivendata.org/competitions/296/cdc-novel-variables/) that uses the same data, but is an unsupervised challenge that does not rely on code execution for submissions. In that competition, competitors can use whichever version of CUDA they prefer.

**Comment by qadn0** [comment]
> @qadn0 I see that you made a couple changes here. There are a few new CUDA packages that get installed via pip:
> 
> ```
> [feature.gpu.pypi-dependencies]
> nvidia-nccl-cu11 = {version = "==2.21.5"}
> nvidia-cuda-runtime-cu11 = {version = "==11.8.89"}
> nvidia-cublas-cu11 = {version = "==11.11.3.6"}
> nvidia-curand-cu11 = {version = "==10.3.0.86"}
> ```
> 
> The goal is to only install CUDA once. All packages should use the existing runtime CUDA that is installed with conda-forge. Did you check whether you are able to use`lmdeploy` successfully without adding the new CUDA packages (ie. with only the CUDA installed via conda-forge)?
> 
> Thank you for working through the alternate installation! We know these things can be finicky.

@klwetstone -- I'm still looking for a solution for this one. Pixi doesn't seem to support `--no-deps` option for `pypi-dependencies`: https://github.com/prefix-dev/pixi/issues/1417. I'm looking for a workaround but haven't found one yet.

**Comment by klwetstone** [comment]
@qadn0 We looked into the addition of `lmdeploy` and `protobuf` to help resolve your outstanding dependency needs. A few takeaways and explanation below. I'm closing this PR, since `protobuf` 4.21.12 is already installed and we're unfortunately unable to support `lmdeploy`.

We appreciate the time you spent working on the pull request, and hope the explanations below are helpful. Good luck!

#### `protobuf`

`protobuf` version 4.21.12 is already installed in the [current environment](https://github.com/drivendataorg/youth-mental-health-runtime/blob/a731bc95eba246604e005a85ffc865bbe5ab07ef/runtime/pixi.lock#L4552). The supported versions of `protobuf` are limited by what is compatible with `tensorflow` 2.14.0, which requires `libprotobuf` 3.21.12. As a result, we cannot support `protobuf` 5.28.x. 

#### `lmdeploy`

Unfortunately, we are unable to support `lmdeploy` because it [requires](https://github.com/InternLM/lmdeploy/blob/178ec7bddcba23d32d9cdc2488e045624390086c/requirements/runtime.txt#L9) downgrading `peft` to 0.11. Now that participants have been building submissions using `peft` 0.12.0, downgrading to 0.11 risks breaking existing submissions. 

FYI, Pixi recently introduced a `no-build-isolation` [option](https://pixi.sh/dev/reference/project_configuration/#no-build-isolation). The way to add `lmdeploy` would have been to install it with pip (like you have), install all other dependencies needed with conda, and specify *not* to isolate `lmdeploy`'s build using `no-build-isolation`. This was introduced in a later version of pixi, so the base Docker images would also need to be updated from `pixi:0.26.1` to `pixi:0.36.0` or similar.

**Pull request closed without merging**
